MODEL_NAME: "AlexNet"
DATASET: "imagenet"
EPOCHS: 30
SCHEDULER:
  STEP_SIZE: 60
  GAMMA: 0.1
NUM_CHANNEL: 3
IMG_SIZE: 224
BATCH_SIZE: 512 # 2048
NUM_CLASSES: 1000
LR:
  INIT: 0.01 # 0.05
USE_AMP: True
NUM_WORKERS: 2
BENCHMARK: True
SEARCH_EPOCHS: 3
VERBOSE: 0