MODEL_NAME: "AlexNet"
DATASET: "cifar10"
EPOCHS: 60
SCHEDULER:
  STEP_SIZE: 30
  GAMMA: 0.1
IMG_SIZE: 256
BATCH_SIZE: 2048
NUM_CLASSES: 10
LR:
  MAX: 0.1
  MIN: 0.0001
USE_AMP: True
NUM_WORKERS: 2
BENCHMARK: True