MODEL_NAME: "ViT"
DATASET: "cifar10"
EPOCHS: 30
SCHEDULER:
  STEP_SIZE: 60
  GAMMA: 0.1
IMG_SIZE: 224
NUM_PATCH_ROW: 7
BATCH_SIZE: 2048
NUM_CLASSES: 10
LR:
  INIT: 0.001
  SEARCH:
    - 0.1
    - 0.05
    - 0.01
    - 0.005
    - 0.001
USE_AMP: True
NUM_WORKERS: 4
BENCHMARK: True
SEARCH_EPOCHS: 5
VERBOSE: 0