MODEL_NAME: "ViT"
DATASET: "imagenet"
EPOCHS: 60
SCHEDULER:
  STEP_SIZE: 30
  GAMMA: 0.1
IMG_SIZE: 224
NUM_PATCH_ROW: 7
BATCH_SIZE: 2048
NUM_CLASSES: 1000
LR: 0.01
USE_AMP: True
NUM_WORKERS: 2
BENCHMARK: True