MODEL_NAME: "ViT"
DATASET: "imagenet"
EPOCHS: 30
SCHEDULER:
  STEP_SIZE: 60
  GAMMA: 0.1
IMG_SIZE: 224
NUM_PATCH_ROW: 7
BATCH_SIZE: 2048
NUM_CLASSES: 1000
LR:
  INIT: 0.005
USE_AMP: True
NUM_WORKERS: 4
BENCHMARK: True
SEARCH_EPOCHS: 3
VERBOSE: 0