MODEL_NAME: "ViT"
DATASET: "cifar10"
EPOCHS: 60
SCHEDULER:
  STEP_SIZE: 20
  GAMMA: 0.1
IMG_SIZE: 32
NUM_PATCH_ROW: 3
BATCH_SIZE: 2048
NUM_CLASSES: 10
LR: 0.01
USE_AMP: True
NUM_WORKERS: 2
BENCHMARK: True